name: posts_clean_architecture
description: posts app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1

  flutter_bloc: ^8.1.3

  dartz: ^0.10.1

  equatable: ^2.0.5

  internet_connection_checker: ^1.0.0+1
  http: ^1.1.0

  shared_preferences: ^2.2.2
  test: ^1.24.9

flutter:


  uses-material-design: true

